package export

import (
	"fmt"
	"strings"
)

// GenerateKustomization returns a kustomization.yaml that applies all exported
// resources in dependency order (namespaces → RBAC → workloads → services).
func GenerateKustomization(result *ExportResult) []byte {
	var sb strings.Builder
	sb.WriteString("apiVersion: kustomize.config.k8s.io/v1beta1\nkind: Kustomization\n\nresources:\n")

	// Cluster-wide first
	for _, r := range result.Cluster.Namespaces {
		sb.WriteString(fmt.Sprintf("  - cluster/namespaces/%s\n", r.Filename))
	}
	for _, r := range result.Cluster.ClusterRoles {
		sb.WriteString(fmt.Sprintf("  - cluster/clusterroles/%s\n", r.Filename))
	}
	for _, r := range result.Cluster.ClusterRoleBindings {
		sb.WriteString(fmt.Sprintf("  - cluster/clusterrolebindings/%s\n", r.Filename))
	}
	for _, r := range result.Cluster.StorageClasses {
		sb.WriteString(fmt.Sprintf("  - cluster/storageclasses/%s\n", r.Filename))
	}

	// Namespaced resources
	for _, ns := range result.Namespaces {
		base := fmt.Sprintf("namespaces/%s", ns.Name)
		for _, r := range ns.ServiceAccounts {
			sb.WriteString(fmt.Sprintf("  - %s/serviceaccounts/%s\n", base, r.Filename))
		}
		for _, r := range ns.ConfigMaps {
			sb.WriteString(fmt.Sprintf("  - %s/configmaps/%s\n", base, r.Filename))
		}
		for _, r := range ns.Secrets {
			sb.WriteString(fmt.Sprintf("  - %s/secrets/%s\n", base, r.Filename))
		}
		for _, r := range ns.Deployments {
			sb.WriteString(fmt.Sprintf("  - %s/deployments/%s\n", base, r.Filename))
		}
		for _, r := range ns.StatefulSets {
			sb.WriteString(fmt.Sprintf("  - %s/statefulsets/%s\n", base, r.Filename))
		}
		for _, r := range ns.Services {
			sb.WriteString(fmt.Sprintf("  - %s/services/%s\n", base, r.Filename))
		}
		for _, r := range ns.Ingresses {
			sb.WriteString(fmt.Sprintf("  - %s/ingresses/%s\n", base, r.Filename))
		}
		for _, r := range ns.HPAs {
			sb.WriteString(fmt.Sprintf("  - %s/hpas/%s\n", base, r.Filename))
		}
	}

	return []byte(sb.String())
}

// GenerateApplyScript returns a bash script that applies resources in order.
func GenerateApplyScript(result *ExportResult) []byte {
	var sb strings.Builder
	sb.WriteString("#!/usr/bin/env bash\n# Generated by cortix export — apply in order\nset -euo pipefail\n\n")

	sb.WriteString("echo '==> Cluster-wide resources'\n")
	sb.WriteString("kubectl apply -f cluster/\n\n")

	for _, ns := range result.Namespaces {
		if len(ns.HelmReleases) > 0 {
			sb.WriteString(fmt.Sprintf("echo '==> Helm releases in %s (install separately)'\n", ns.Name))
			for _, hr := range ns.HelmReleases {
				sb.WriteString(fmt.Sprintf("# helm upgrade --install %s <chart> -n %s -f namespaces/%s/helm/%s-values.yaml\n", hr.Name, hr.Namespace, ns.Name, hr.Name))
			}
			sb.WriteString("\n")
		}
		sb.WriteString(fmt.Sprintf("echo '==> Namespace: %s'\n", ns.Name))
		sb.WriteString(fmt.Sprintf("kubectl apply -f namespaces/%s/\n\n", ns.Name))
	}

	return []byte(sb.String())
}

// GenerateWarnings returns a human-readable WARNINGS.md from collected warnings.
func GenerateWarnings(result *ExportResult) []byte {
	all := append([]string{}, result.Warnings...)
	all = append(all, result.Cluster.Warnings...)
	for _, ns := range result.Namespaces {
		for _, w := range ns.Warnings {
			all = append(all, fmt.Sprintf("[%s] %s", ns.Name, w))
		}
	}
	if len(all) == 0 {
		return nil
	}

	var sb strings.Builder
	sb.WriteString("# Export Warnings\n\nThe following issues were encountered during export:\n\n")
	for _, w := range all {
		sb.WriteString(fmt.Sprintf("- %s\n", w))
	}
	return []byte(sb.String())
}
