package export

import "fmt"

// readmeTemplate is the README.md written at the root of the export directory.
const readmeTemplate = `# Cortix Export — %s

Generated by [cortix](https://github.com/JunaCodeBase/cortix) on %s.

## ⚠️  Before applying

1. **Replace all secret placeholders** — search for ` + "`PLACEHOLDER_REPLACE_ME`" + ` and fill in real values.
2. **Review Helm releases** — see ` + "`HELM_RELEASES.md`" + ` for charts that must be installed separately.
3. **Validate with --dry-run** — ` + "`kubectl apply --dry-run=server -f .`" + `

## Structure

` + "```" + `
.
├── cluster/                   # Cluster-wide resources (RBAC, StorageClasses, Namespaces)
├── namespaces/<name>/         # Per-namespace resources
│   ├── deployments/
│   ├── statefulsets/
│   ├── services/
│   ├── ingresses/
│   ├── configmaps/
│   ├── secrets/               # All values are PLACEHOLDER_REPLACE_ME
│   ├── serviceaccounts/
│   ├── hpas/
│   └── helm/                  # values.yaml stubs for Helm-managed releases
├── kustomization.yaml
├── apply.sh
└── WARNINGS.md                # Any issues encountered during export
` + "```" + `

## Apply

` + "```bash" + `
# Review first
kubectl apply --dry-run=server -f .

# Apply
bash apply.sh
` + "```" + `
`

// helmReleasesTemplate is the HELM_RELEASES.md written when Helm releases are detected.
const helmReleasesTemplate = `# Helm Releases

The following releases were detected but NOT exported as raw YAML.
Install them with Helm before applying the remaining resources.

`

// HelmReleasesDoc builds HELM_RELEASES.md content listing all detected releases.
func HelmReleasesDoc(result *ExportResult) []byte {
	if result.HelmCount == 0 {
		return nil
	}
	out := helmReleasesTemplate
	for _, ns := range result.Namespaces {
		for _, hr := range ns.HelmReleases {
			out += fmt.Sprintf("## %s (namespace: %s)\n\n", hr.Name, hr.Namespace)
			out += fmt.Sprintf("```bash\nhelm upgrade --install %s <chart> \\\n  --namespace %s \\\n  -f namespaces/%s/helm/%s-values.yaml\n```\n\n", hr.Name, hr.Namespace, ns.Name, hr.Name)
		}
	}
	return []byte(out)
}

// HelmValuesStub returns a minimal values.yaml stub for a Helm release.
func HelmValuesStub(hr HelmRelease) []byte {
	return []byte(fmt.Sprintf(`# Helm values stub for release: %s
# Replace with your actual values before installing.
# helm upgrade --install %s <chart> -n %s -f this-file.yaml

# replicaCount: 1
# image:
#   repository: your-image
#   tag: latest
`, hr.Name, hr.Name, hr.Namespace))
}
